### ISSUE TITLE
Zooming in an image, being unable to see the top

### ISSUE THREAD

**Issue by Zorrototo** [jasadams/imagezoom#34]
Firefox 47.0.1
Windows 7 x64 Ultimate
1680*1050
- In the browser, show only an image (not a web page, just an image link like http://i.imgur.com/XqybYsf.png )
- Zoom in the image until the top of image is off-screen
- Try to move around to see all the parts of the image, you're unable to see the top it is off-screen and you have to unzoom to be able to see the top part. Other parts (right, left, bottom) can be visible by moving.

**Comment by PierreMec** [comment]
I've been having the exact same issue for several months now. If images are zoomed larger than the height of the page, the top of the image is cut off and it will not scroll up to view the part of the image that is off the screen.  But as you said, the left/right scroll does work as it should.
 It's a real shame, because Image Zoom is by far the best "zooming" utility on the web.  In fact, I prefer the Opera browser in general but stick with buggy Firefox solely because the Image Zoom add-on isn't available for Opera!   I hope they can get this bug ironed out that cuts off the tops of zoomed photos.

**Comment by Zorrototo** [comment]
Look down and read ;) you have a fix https://github.com/jasadams/imagezoom/issues/33#issuecomment-238784498
